package matroska

import "honnef.co/go/xcapture/internal/matroska/ebml"

func Segment(c ...ebml.Object) ebml.Element                     { return ebml.Element{0x18538067, c} }
func SeekHead(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x114D9B74, c} }
func Seek(c ...ebml.Object) ebml.Element                        { return ebml.Element{0x4DBB, c} }
func SeekID(c ...ebml.Object) ebml.Element                      { return ebml.Element{0x53AB, c} }
func SeekPosition(c ...ebml.Object) ebml.Element                { return ebml.Element{0x53AC, c} }
func Info(c ...ebml.Object) ebml.Element                        { return ebml.Element{0x1549A966, c} }
func SegmentUID(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x73A4, c} }
func SegmentFilename(c ...ebml.Object) ebml.Element             { return ebml.Element{0x7384, c} }
func PrevUID(c ...ebml.Object) ebml.Element                     { return ebml.Element{0x3CB923, c} }
func PrevFilename(c ...ebml.Object) ebml.Element                { return ebml.Element{0x3C83AB, c} }
func NextUID(c ...ebml.Object) ebml.Element                     { return ebml.Element{0x3EB923, c} }
func NextFilename(c ...ebml.Object) ebml.Element                { return ebml.Element{0x3E83BB, c} }
func SegmentFamily(c ...ebml.Object) ebml.Element               { return ebml.Element{0x4444, c} }
func ChapterTranslate(c ...ebml.Object) ebml.Element            { return ebml.Element{0x6924, c} }
func ChapterTranslateEditionUID(c ...ebml.Object) ebml.Element  { return ebml.Element{0x69FC, c} }
func ChapterTranslateCodec(c ...ebml.Object) ebml.Element       { return ebml.Element{0x69BF, c} }
func ChapterTranslateID(c ...ebml.Object) ebml.Element          { return ebml.Element{0x69A5, c} }
func TimecodeScale(c ...ebml.Object) ebml.Element               { return ebml.Element{0x2AD7B1, c} }
func Duration(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x4489, c} }
func DateUTC(c ...ebml.Object) ebml.Element                     { return ebml.Element{0x4461, c} }
func Title(c ...ebml.Object) ebml.Element                       { return ebml.Element{0x7BA9, c} }
func MuxingApp(c ...ebml.Object) ebml.Element                   { return ebml.Element{0x4D80, c} }
func WritingApp(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x5741, c} }
func Cluster(c ...ebml.Object) ebml.Element                     { return ebml.Element{0x1F43B675, c} }
func Timecode(c ...ebml.Object) ebml.Element                    { return ebml.Element{0xE7, c} }
func SilentTracks(c ...ebml.Object) ebml.Element                { return ebml.Element{0x5854, c} }
func SilentTrackNumber(c ...ebml.Object) ebml.Element           { return ebml.Element{0x58D7, c} }
func Position(c ...ebml.Object) ebml.Element                    { return ebml.Element{0xA7, c} }
func PrevSize(c ...ebml.Object) ebml.Element                    { return ebml.Element{0xAB, c} }
func SimpleBlock(c ...ebml.Object) ebml.Element                 { return ebml.Element{0xA3, c} }
func BlockGroup(c ...ebml.Object) ebml.Element                  { return ebml.Element{0xA0, c} }
func Block(c ...ebml.Object) ebml.Element                       { return ebml.Element{0xA1, c} }
func BlockVirtual(c ...ebml.Object) ebml.Element                { return ebml.Element{0xA2, c} }
func BlockAdditions(c ...ebml.Object) ebml.Element              { return ebml.Element{0x75A1, c} }
func BlockMore(c ...ebml.Object) ebml.Element                   { return ebml.Element{0xA6, c} }
func BlockAddID(c ...ebml.Object) ebml.Element                  { return ebml.Element{0xEE, c} }
func BlockAdditional(c ...ebml.Object) ebml.Element             { return ebml.Element{0xA5, c} }
func BlockDuration(c ...ebml.Object) ebml.Element               { return ebml.Element{0x9B, c} }
func ReferencePriority(c ...ebml.Object) ebml.Element           { return ebml.Element{0xFA, c} }
func ReferenceBlock(c ...ebml.Object) ebml.Element              { return ebml.Element{0xFB, c} }
func ReferenceVirtual(c ...ebml.Object) ebml.Element            { return ebml.Element{0xFD, c} }
func CodecState(c ...ebml.Object) ebml.Element                  { return ebml.Element{0xA4, c} }
func DiscardPadding(c ...ebml.Object) ebml.Element              { return ebml.Element{0x75A2, c} }
func Slices(c ...ebml.Object) ebml.Element                      { return ebml.Element{0x8E, c} }
func TimeSlice(c ...ebml.Object) ebml.Element                   { return ebml.Element{0xE8, c} }
func LaceNumber(c ...ebml.Object) ebml.Element                  { return ebml.Element{0xCC, c} }
func FrameNumber(c ...ebml.Object) ebml.Element                 { return ebml.Element{0xCD, c} }
func BlockAdditionID(c ...ebml.Object) ebml.Element             { return ebml.Element{0xCB, c} }
func Delay(c ...ebml.Object) ebml.Element                       { return ebml.Element{0xCE, c} }
func SliceDuration(c ...ebml.Object) ebml.Element               { return ebml.Element{0xCF, c} }
func ReferenceFrame(c ...ebml.Object) ebml.Element              { return ebml.Element{0xC8, c} }
func ReferenceOffset(c ...ebml.Object) ebml.Element             { return ebml.Element{0xC9, c} }
func ReferenceTimeCode(c ...ebml.Object) ebml.Element           { return ebml.Element{0xCA, c} }
func EncryptedBlock(c ...ebml.Object) ebml.Element              { return ebml.Element{0xAF, c} }
func Tracks(c ...ebml.Object) ebml.Element                      { return ebml.Element{0x1654AE6B, c} }
func TrackEntry(c ...ebml.Object) ebml.Element                  { return ebml.Element{0xAE, c} }
func TrackNumber(c ...ebml.Object) ebml.Element                 { return ebml.Element{0xD7, c} }
func TrackUID(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x73C5, c} }
func TrackType(c ...ebml.Object) ebml.Element                   { return ebml.Element{0x83, c} }
func FlagEnabled(c ...ebml.Object) ebml.Element                 { return ebml.Element{0xB9, c} }
func FlagDefault(c ...ebml.Object) ebml.Element                 { return ebml.Element{0x88, c} }
func FlagForced(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x55AA, c} }
func FlagLacing(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x9C, c} }
func MinCache(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x6DE7, c} }
func MaxCache(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x6DF8, c} }
func DefaultDuration(c ...ebml.Object) ebml.Element             { return ebml.Element{0x23E383, c} }
func DefaultDecodedFieldDuration(c ...ebml.Object) ebml.Element { return ebml.Element{0x234E7A, c} }
func TrackTimecodeScale(c ...ebml.Object) ebml.Element          { return ebml.Element{0x23314F, c} }
func TrackOffset(c ...ebml.Object) ebml.Element                 { return ebml.Element{0x537F, c} }
func MaxBlockAdditionID(c ...ebml.Object) ebml.Element          { return ebml.Element{0x55EE, c} }
func Name(c ...ebml.Object) ebml.Element                        { return ebml.Element{0x536E, c} }
func Language(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x22B59C, c} }
func CodecID(c ...ebml.Object) ebml.Element                     { return ebml.Element{0x86, c} }
func CodecPrivate(c ...ebml.Object) ebml.Element                { return ebml.Element{0x63A2, c} }
func CodecName(c ...ebml.Object) ebml.Element                   { return ebml.Element{0x258688, c} }
func AttachmentLink(c ...ebml.Object) ebml.Element              { return ebml.Element{0x7446, c} }
func CodecSettings(c ...ebml.Object) ebml.Element               { return ebml.Element{0x3A9697, c} }
func CodecInfoURL(c ...ebml.Object) ebml.Element                { return ebml.Element{0x3B4040, c} }
func CodecDownloadURL(c ...ebml.Object) ebml.Element            { return ebml.Element{0x26B240, c} }
func CodecDecodeAll(c ...ebml.Object) ebml.Element              { return ebml.Element{0xAA, c} }
func TrackOverlay(c ...ebml.Object) ebml.Element                { return ebml.Element{0x6FAB, c} }
func CodecDelay(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x56AA, c} }
func SeekPreRoll(c ...ebml.Object) ebml.Element                 { return ebml.Element{0x56BB, c} }
func TrackTranslate(c ...ebml.Object) ebml.Element              { return ebml.Element{0x6624, c} }
func TrackTranslateEditionUID(c ...ebml.Object) ebml.Element    { return ebml.Element{0x66FC, c} }
func TrackTranslateCodec(c ...ebml.Object) ebml.Element         { return ebml.Element{0x66BF, c} }
func TrackTranslateTrackID(c ...ebml.Object) ebml.Element       { return ebml.Element{0x66A5, c} }
func Video(c ...ebml.Object) ebml.Element                       { return ebml.Element{0xE0, c} }
func FlagInterlaced(c ...ebml.Object) ebml.Element              { return ebml.Element{0x9A, c} }
func FieldOrder(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x9D, c} }
func StereoMode(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x53B8, c} }
func AlphaMode(c ...ebml.Object) ebml.Element                   { return ebml.Element{0x53C0, c} }
func OldStereoMode(c ...ebml.Object) ebml.Element               { return ebml.Element{0x53B9, c} }
func PixelWidth(c ...ebml.Object) ebml.Element                  { return ebml.Element{0xB0, c} }
func PixelHeight(c ...ebml.Object) ebml.Element                 { return ebml.Element{0xBA, c} }
func PixelCropBottom(c ...ebml.Object) ebml.Element             { return ebml.Element{0x54AA, c} }
func PixelCropTop(c ...ebml.Object) ebml.Element                { return ebml.Element{0x54BB, c} }
func PixelCropLeft(c ...ebml.Object) ebml.Element               { return ebml.Element{0x54CC, c} }
func PixelCropRight(c ...ebml.Object) ebml.Element              { return ebml.Element{0x54DD, c} }
func DisplayWidth(c ...ebml.Object) ebml.Element                { return ebml.Element{0x54B0, c} }
func DisplayHeight(c ...ebml.Object) ebml.Element               { return ebml.Element{0x54BA, c} }
func DisplayUnit(c ...ebml.Object) ebml.Element                 { return ebml.Element{0x54B2, c} }
func AspectRatioType(c ...ebml.Object) ebml.Element             { return ebml.Element{0x54B3, c} }
func ColourSpace(c ...ebml.Object) ebml.Element                 { return ebml.Element{0x2EB524, c} }
func GammaValue(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x2FB523, c} }
func FrameRate(c ...ebml.Object) ebml.Element                   { return ebml.Element{0x2383E3, c} }
func Colour(c ...ebml.Object) ebml.Element                      { return ebml.Element{0x55B0, c} }
func MatrixCoefficients(c ...ebml.Object) ebml.Element          { return ebml.Element{0x55B1, c} }
func BitsPerChannel(c ...ebml.Object) ebml.Element              { return ebml.Element{0x55B2, c} }
func ChromaSubsamplingHorz(c ...ebml.Object) ebml.Element       { return ebml.Element{0x55B3, c} }
func ChromaSubsamplingVert(c ...ebml.Object) ebml.Element       { return ebml.Element{0x55B4, c} }
func CbSubsamplingHorz(c ...ebml.Object) ebml.Element           { return ebml.Element{0x55B5, c} }
func CbSubsamplingVert(c ...ebml.Object) ebml.Element           { return ebml.Element{0x55B6, c} }
func ChromaSitingHorz(c ...ebml.Object) ebml.Element            { return ebml.Element{0x55B7, c} }
func ChromaSitingVert(c ...ebml.Object) ebml.Element            { return ebml.Element{0x55B8, c} }
func Range(c ...ebml.Object) ebml.Element                       { return ebml.Element{0x55B9, c} }
func TransferCharacteristics(c ...ebml.Object) ebml.Element     { return ebml.Element{0x55BA, c} }
func Primaries(c ...ebml.Object) ebml.Element                   { return ebml.Element{0x55BB, c} }
func MaxCLL(c ...ebml.Object) ebml.Element                      { return ebml.Element{0x55BC, c} }
func MaxFALL(c ...ebml.Object) ebml.Element                     { return ebml.Element{0x55BD, c} }
func MasteringMetadata(c ...ebml.Object) ebml.Element           { return ebml.Element{0x55D0, c} }
func PrimaryRChromaticityX(c ...ebml.Object) ebml.Element       { return ebml.Element{0x55D1, c} }
func PrimaryRChromaticityY(c ...ebml.Object) ebml.Element       { return ebml.Element{0x55D2, c} }
func PrimaryGChromaticityX(c ...ebml.Object) ebml.Element       { return ebml.Element{0x55D3, c} }
func PrimaryGChromaticityY(c ...ebml.Object) ebml.Element       { return ebml.Element{0x55D4, c} }
func PrimaryBChromaticityX(c ...ebml.Object) ebml.Element       { return ebml.Element{0x55D5, c} }
func PrimaryBChromaticityY(c ...ebml.Object) ebml.Element       { return ebml.Element{0x55D6, c} }
func WhitePointChromaticityX(c ...ebml.Object) ebml.Element     { return ebml.Element{0x55D7, c} }
func WhitePointChromaticityY(c ...ebml.Object) ebml.Element     { return ebml.Element{0x55D8, c} }
func LuminanceMax(c ...ebml.Object) ebml.Element                { return ebml.Element{0x55D9, c} }
func LuminanceMin(c ...ebml.Object) ebml.Element                { return ebml.Element{0x55DA, c} }
func Audio(c ...ebml.Object) ebml.Element                       { return ebml.Element{0xE1, c} }
func SamplingFrequency(c ...ebml.Object) ebml.Element           { return ebml.Element{0xB5, c} }
func OutputSamplingFrequency(c ...ebml.Object) ebml.Element     { return ebml.Element{0x78B5, c} }
func Channels(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x9F, c} }
func ChannelPositions(c ...ebml.Object) ebml.Element            { return ebml.Element{0x7D7B, c} }
func BitDepth(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x6264, c} }
func TrackOperation(c ...ebml.Object) ebml.Element              { return ebml.Element{0xE2, c} }
func TrackCombinePlanes(c ...ebml.Object) ebml.Element          { return ebml.Element{0xE3, c} }
func TrackPlane(c ...ebml.Object) ebml.Element                  { return ebml.Element{0xE4, c} }
func TrackPlaneUID(c ...ebml.Object) ebml.Element               { return ebml.Element{0xE5, c} }
func TrackPlaneType(c ...ebml.Object) ebml.Element              { return ebml.Element{0xE6, c} }
func TrackJoinBlocks(c ...ebml.Object) ebml.Element             { return ebml.Element{0xE9, c} }
func TrackJoinUID(c ...ebml.Object) ebml.Element                { return ebml.Element{0xED, c} }
func TrickTrackUID(c ...ebml.Object) ebml.Element               { return ebml.Element{0xC0, c} }
func TrickTrackSegmentUID(c ...ebml.Object) ebml.Element        { return ebml.Element{0xC1, c} }
func TrickTrackFlag(c ...ebml.Object) ebml.Element              { return ebml.Element{0xC6, c} }
func TrickMasterTrackUID(c ...ebml.Object) ebml.Element         { return ebml.Element{0xC7, c} }
func TrickMasterTrackSegmentUID(c ...ebml.Object) ebml.Element  { return ebml.Element{0xC4, c} }
func ContentEncodings(c ...ebml.Object) ebml.Element            { return ebml.Element{0x6D80, c} }
func ContentEncoding(c ...ebml.Object) ebml.Element             { return ebml.Element{0x6240, c} }
func ContentEncodingOrder(c ...ebml.Object) ebml.Element        { return ebml.Element{0x5031, c} }
func ContentEncodingScope(c ...ebml.Object) ebml.Element        { return ebml.Element{0x5032, c} }
func ContentEncodingType(c ...ebml.Object) ebml.Element         { return ebml.Element{0x5033, c} }
func ContentCompression(c ...ebml.Object) ebml.Element          { return ebml.Element{0x5034, c} }
func ContentCompAlgo(c ...ebml.Object) ebml.Element             { return ebml.Element{0x4254, c} }
func ContentCompSettings(c ...ebml.Object) ebml.Element         { return ebml.Element{0x4255, c} }
func ContentEncryption(c ...ebml.Object) ebml.Element           { return ebml.Element{0x5035, c} }
func ContentEncAlgo(c ...ebml.Object) ebml.Element              { return ebml.Element{0x47E1, c} }
func ContentEncKeyID(c ...ebml.Object) ebml.Element             { return ebml.Element{0x47E2, c} }
func ContentSignature(c ...ebml.Object) ebml.Element            { return ebml.Element{0x47E3, c} }
func ContentSigKeyID(c ...ebml.Object) ebml.Element             { return ebml.Element{0x47E4, c} }
func ContentSigAlgo(c ...ebml.Object) ebml.Element              { return ebml.Element{0x47E5, c} }
func ContentSigHashAlgo(c ...ebml.Object) ebml.Element          { return ebml.Element{0x47E6, c} }
func Cues(c ...ebml.Object) ebml.Element                        { return ebml.Element{0x1C53BB6B, c} }
func CuePoint(c ...ebml.Object) ebml.Element                    { return ebml.Element{0xBB, c} }
func CueTime(c ...ebml.Object) ebml.Element                     { return ebml.Element{0xB3, c} }
func CueTrackPositions(c ...ebml.Object) ebml.Element           { return ebml.Element{0xB7, c} }
func CueTrack(c ...ebml.Object) ebml.Element                    { return ebml.Element{0xF7, c} }
func CueClusterPosition(c ...ebml.Object) ebml.Element          { return ebml.Element{0xF1, c} }
func CueRelativePosition(c ...ebml.Object) ebml.Element         { return ebml.Element{0xF0, c} }
func CueDuration(c ...ebml.Object) ebml.Element                 { return ebml.Element{0xB2, c} }
func CueBlockNumber(c ...ebml.Object) ebml.Element              { return ebml.Element{0x5378, c} }
func CueCodecState(c ...ebml.Object) ebml.Element               { return ebml.Element{0xEA, c} }
func CueReference(c ...ebml.Object) ebml.Element                { return ebml.Element{0xDB, c} }
func CueRefTime(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x96, c} }
func CueRefCluster(c ...ebml.Object) ebml.Element               { return ebml.Element{0x97, c} }
func CueRefNumber(c ...ebml.Object) ebml.Element                { return ebml.Element{0x535F, c} }
func CueRefCodecState(c ...ebml.Object) ebml.Element            { return ebml.Element{0xEB, c} }
func Attachments(c ...ebml.Object) ebml.Element                 { return ebml.Element{0x1941A469, c} }
func AttachedFile(c ...ebml.Object) ebml.Element                { return ebml.Element{0x61A7, c} }
func FileDescription(c ...ebml.Object) ebml.Element             { return ebml.Element{0x467E, c} }
func FileName(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x466E, c} }
func FileMimeType(c ...ebml.Object) ebml.Element                { return ebml.Element{0x4660, c} }
func FileData(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x465C, c} }
func FileUID(c ...ebml.Object) ebml.Element                     { return ebml.Element{0x46AE, c} }
func FileReferral(c ...ebml.Object) ebml.Element                { return ebml.Element{0x4675, c} }
func FileUsedStartTime(c ...ebml.Object) ebml.Element           { return ebml.Element{0x4661, c} }
func FileUsedEndTime(c ...ebml.Object) ebml.Element             { return ebml.Element{0x4662, c} }
func Chapters(c ...ebml.Object) ebml.Element                    { return ebml.Element{0x1043A770, c} }
func EditionEntry(c ...ebml.Object) ebml.Element                { return ebml.Element{0x45B9, c} }
func EditionUID(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x45BC, c} }
func EditionFlagHidden(c ...ebml.Object) ebml.Element           { return ebml.Element{0x45BD, c} }
func EditionFlagDefault(c ...ebml.Object) ebml.Element          { return ebml.Element{0x45DB, c} }
func EditionFlagOrdered(c ...ebml.Object) ebml.Element          { return ebml.Element{0x45DD, c} }
func ChapterAtom(c ...ebml.Object) ebml.Element                 { return ebml.Element{0xB6, c} }
func ChapterUID(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x73C4, c} }
func ChapterStringUID(c ...ebml.Object) ebml.Element            { return ebml.Element{0x5654, c} }
func ChapterTimeStart(c ...ebml.Object) ebml.Element            { return ebml.Element{0x91, c} }
func ChapterTimeEnd(c ...ebml.Object) ebml.Element              { return ebml.Element{0x92, c} }
func ChapterFlagHidden(c ...ebml.Object) ebml.Element           { return ebml.Element{0x98, c} }
func ChapterFlagEnabled(c ...ebml.Object) ebml.Element          { return ebml.Element{0x4598, c} }
func ChapterSegmentUID(c ...ebml.Object) ebml.Element           { return ebml.Element{0x6E67, c} }
func ChapterSegmentEditionUID(c ...ebml.Object) ebml.Element    { return ebml.Element{0x6EBC, c} }
func ChapterPhysicalEquiv(c ...ebml.Object) ebml.Element        { return ebml.Element{0x63C3, c} }
func ChapterTrack(c ...ebml.Object) ebml.Element                { return ebml.Element{0x8F, c} }
func ChapterTrackNumber(c ...ebml.Object) ebml.Element          { return ebml.Element{0x89, c} }
func ChapterDisplay(c ...ebml.Object) ebml.Element              { return ebml.Element{0x80, c} }
func ChapString(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x85, c} }
func ChapLanguage(c ...ebml.Object) ebml.Element                { return ebml.Element{0x437C, c} }
func ChapCountry(c ...ebml.Object) ebml.Element                 { return ebml.Element{0x437E, c} }
func ChapProcess(c ...ebml.Object) ebml.Element                 { return ebml.Element{0x6944, c} }
func ChapProcessCodecID(c ...ebml.Object) ebml.Element          { return ebml.Element{0x6955, c} }
func ChapProcessPrivate(c ...ebml.Object) ebml.Element          { return ebml.Element{0x450D, c} }
func ChapProcessCommand(c ...ebml.Object) ebml.Element          { return ebml.Element{0x6911, c} }
func ChapProcessTime(c ...ebml.Object) ebml.Element             { return ebml.Element{0x6922, c} }
func ChapProcessData(c ...ebml.Object) ebml.Element             { return ebml.Element{0x6933, c} }
func Tags(c ...ebml.Object) ebml.Element                        { return ebml.Element{0x1254C367, c} }
func Tag(c ...ebml.Object) ebml.Element                         { return ebml.Element{0x7373, c} }
func Targets(c ...ebml.Object) ebml.Element                     { return ebml.Element{0x63C0, c} }
func TargetTypeValue(c ...ebml.Object) ebml.Element             { return ebml.Element{0x68CA, c} }
func TargetType(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x63CA, c} }
func TagTrackUID(c ...ebml.Object) ebml.Element                 { return ebml.Element{0x63C5, c} }
func TagEditionUID(c ...ebml.Object) ebml.Element               { return ebml.Element{0x63C9, c} }
func TagChapterUID(c ...ebml.Object) ebml.Element               { return ebml.Element{0x63C4, c} }
func TagAttachmentUID(c ...ebml.Object) ebml.Element            { return ebml.Element{0x63C6, c} }
func SimpleTag(c ...ebml.Object) ebml.Element                   { return ebml.Element{0x67C8, c} }
func TagName(c ...ebml.Object) ebml.Element                     { return ebml.Element{0x45A3, c} }
func TagLanguage(c ...ebml.Object) ebml.Element                 { return ebml.Element{0x447A, c} }
func TagDefault(c ...ebml.Object) ebml.Element                  { return ebml.Element{0x4484, c} }
func TagString(c ...ebml.Object) ebml.Element                   { return ebml.Element{0x4487, c} }
func TagBinary(c ...ebml.Object) ebml.Element                   { return ebml.Element{0x4485, c} }
